### ISSUE TITLE
How to train model for other language?

### ISSUE THREAD

**Issue by wushixian** [Shivanandroy/KeyPhraseTransformer#1]
The package is really good, but I want to use it for other language, and I tried to modify the model path and use other T5 model, but the model cannot be loaded? May I know how to train a model from scratch?
Thanks a lot.

**Comment by Shivanandroy** [comment]
@wushixian: KeyPhraseTransformer, under the hood, uses a T5 model (but trained in a specific way). If you want to extract keywords from other languages, I would suggest the following:
- First, train a **mT5** model on the dataset of your language. You can use **SimpleT5** (https://github.com/Shivanandroy/simpleT5) to train it in just 3 lines of code
- Format of your dataset should be - (in target text, keywords must be separated with pipe " | ":
`source_text = "Wushixian is a NLP expert."`
`target_text: "Wushixian | NLP expert"`
- Then, you can use **KeyPhraseTransformer** to use this model as below:
```python
from keyphrasetransformer import KeyPhraseTransformer
kp = KeyPhraseTransformer(model_type="mt5", model_name="<your trained mT5 model path>")
```

**Comment by wushixian** [comment]
Thanks a lot, I'll try to train a model.

**Comment by z-arabi** [comment]
Hello,

I tried to fine tune this model on persian language. I have a question. What will happen when we call this function?
It didn't take me long time to execute. How exactly the fine tuning happens in this model?

`kp = KeyPhraseTransformer(model_type="mt5", model_name="folder")`
